#!/usr/bin/env bash

# Remove any old builds
rm -rf build *.egg-info .eggs dist

# Build the package
python setup.py sdist
python setup.py bdist_wheel --universal

# Upload package and remove local build files
twine upload dist/*

echo "Removing build files..."
rm -rf build *.egg-info .eggs dist